//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSheep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Round
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_Round()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int Round_ID { get; set; }
        public int Game_ID { get; set; }
        public Nullable<int> Round_Num { get; set; }
        public int Player_Turn { get; set; }
        public Nullable<byte> Leading_Card { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
    }
}
