//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSheep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hand
    {
        public int Hand_Player { get; set; }
        public int Hand_Game { get; set; }
        public byte Hand_Card { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
