//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSheep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoresheet
    {
        public int Score_ID { get; set; }
        public int Table_ID { get; set; }
        public int Player_ID { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Table_Match Table_Match { get; set; }
    }
}
